services:
  app:
    build: .
    container_name: axsessgard
    expose:
      - "8080"
    networks:
      - internal

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./htpasswd:/etc/nginx/.htpasswd:ro
    networks:
      - internal
      - bridge

networks:
  internal:
    driver: bridge
    internal: true
  bridge:
    driver: bridge
