openapi: 3.0.0
info:
  title: AxsessGard API
  version: 1.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  description: |
    AxsessGard is an access control microservice giving access control advices to other services.
    Applications may protecting their assets can ask the client to get a signed JWT containing an access advice.
    Based on teh advice the application will or will not allow the access to the resource.
paths:
  /axsg/permissions:
    get:
      summary: Get permissions
      description: |
        Get the permissions, specifically the list of actions that a certain `user` bearing `roles` is allowed to perform on an object controlled by the `policy`.
        The `user`, `policy` and the list of `roles` are claims delivered by the JWT in the authentication header.
        The JWT has to be signed by one of the known applications configured in the application.
      operationId: getPermissions
      tags:
        - api
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string
  /axsg/acl/{name}:
    get:
      summary: Get ACL content
      operationId: getAcl
      tags:
        - api
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
        - in: header
          name: x-user-id
          schema:
            type: string
        - in: header
          name: Authorization
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string
    put:
      summary: Update ACL content
      operationId: putAcl
      tags:
        - api
      parameters:
        - in: header
          name: x-user-id
          required: false
          schema:
            type: string
        - in: header
          name: Authorization
          required: false
          schema:
            type: string
        - in: path
          name: name
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: ACL object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string
  /axsg/acl:
    post:
      summary: Insert ACL content
      operationId: postAcl
      tags:
        - api
      parameters:
        - in: header
          name: x-user-id
          schema:
            type: string
        - in: header
          name: Authorization
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: ACL object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string
  /axsg/put/acl/{name}:
    get:
      summary: Get ACL content
      operationId: getPutPermission
      tags:
        - api
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
        - in: header
          name: x-user-id
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string
  /axsg/post/acl:
    get:
      summary: Get ACL content
      operationId: getPostPermission
      tags:
        - api
      parameters:
        - in: header
          name: x-user-id
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string
